<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Deal Information')?></h4>
    </div>
    <fieldset>

        <legend><?php echo $this->__('Deal Information')?></legend>
        <table cellspacing="0" id="table_groupdeal" class="form-list">
            <tbody>
                <tr>
                    <td class="label"><label for="deal_tier_id"><?php echo $this->__('Tier Id')?></label></td>
                    <td class="value">
                        <input type="text" id="deal_tier_id" name="deal[tier_id]" class="required-entry input-text required-entry"/>
                        <button style="" onclick="" class="scalable save" type="button" title="Save" id="deal_load_tier">
                            <span style="line-height: 0 !important;"><span><span><?php echo $this->__('Load Tier Price')?></span></span></span>
                        </button>
                    </td>
                </tr>

                <tr class="deal-tier-table" style="">
                    <td class="label"><label for="deal_tier_price"><?php echo $this->__('Tier Price')?></label></td>
                    <td class="value grid">
                        <table cellspacing="0" id="deal_tier_price" class="border">
                            <colgroup>
                                <col width="117">
                                <col width="172">
                            </colgroup>
                            <thead>
                            <tr class="headings">
                                <th>Qty</th>
                                <th>Price</th>
                            </tr>
                            </thead>
                            <tbody id="tier_price_container">
                                <tr>
                                    <td class="nobr">
                                        <input type="text" id="tier_price_row_0_qty" value="" name="tier_price[0][tier_qty]" class="required-entry input-text required-entry dt_qty required-entry validate-greater-than-zero"> <small class="nobr">and above</small>
                                    </td>
                                    <td class="last">
                                        <input type="text" id="tier_price_row_0_price" value="" name="tier_price[0][tier_price]" class="required-entry input-text required-entry dt_price required-entry">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="nobr">
                                        <input type="text" id="tier_price_row_1_qty" value="" name="tier_price[1][tier_qty]" class="required-entry input-text required-entry dt_qty required-entry validate-greater-than-zero"> <small class="nobr">and above</small>
                                    </td>
                                    <td class="last">
                                        <input type="text" id="tier_price_row_1_price" value="" name="tier_price[1][tier_price]" class="required-entry input-text required-entry dt_price required-entry">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>

                <tr>
                    <td class="label"><label for="deal_name"><?php echo $this->__('Deal Name')?></label></td>
                    <td class="value">
                        <input type="text" id="deal_name" name="deal[group_deal_name]" class="input-text"/>
                    </td>
                </tr>

                <tr>
                    <td class="label"><label for="deal_name"><?php echo $this->__('Status')?></label></td>
                    <td class="value">
                        <select class="select" name="deal[is_active]" id="deal_status">
                            <option value="0"><?php echo $this->__('Disabled')?></option>
                            <option selected="selected" value="1"><?php echo $this->__('Enabled')?></option>
                        </select>
                    </td>
                </tr>

                <tr>
                    <td class="label"><label for="deal_from_date">From Date</label></td>
                    <td class="value">
                        <input type="text" style="width:110px !important;" class=" input-text" value="" id="deal_from_date" name="deal[deal_from_date]">
                        <img style="" title="Select Date" id="deal_from_date_trig" class="v-middle" alt="" src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>">
                        <script type="text/javascript">
                            //&lt;![CDATA[
                            Calendar.setup({
                                inputField: "deal_from_date",
                                ifFormat: "%m/%e/%Y",
                                showsTime: false,
                                button: "deal_from_date_trig",
                                align: "Bl",
                                singleClick : true
                            });
                            //]]&gt;
                        </script>
                    </td>
                </tr>

                <tr>
                    <td class="label"><label for="deal_to_date">From Date</label></td>
                    <td class="value">
                        <input type="text" style="width:110px !important;" class=" input-text" value="" id="deal_to_date" name="deal[deal_to_date]">
                        <img style="" title="Select Date" id="deal_to_date_trig" class="v-middle" alt="" src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>">
                        <script type="text/javascript">
                            //&lt;![CDATA[
                            Calendar.setup({
                                inputField: "deal_to_date",
                                ifFormat: "%m/%e/%Y",
                                showsTime: false,
                                button: "deal_to_date_trig",
                                align: "Bl",
                                singleClick : true
                            });
                            //]]&gt;
                        </script>
                    </td>
                </tr>

                <tr>
                    <td class="label"><label for="deal_current_price"><?php echo $this->__('Description')?></label></td>
                    <td class="value">
                        <textarea cols="15" rows="2" class="textarea" name="deal[deal_description]" id="deal_description">

                        </textarea>
                    </td>
                </tr>

                <tr>
                    <td class="label"><label for="deal_current_price"><?php echo $this->__('Current Price')?></label></td>
                    <td class="value">
                        <input type="text" id="deal_current_price" name="deal[current_price]" class="input-text" disabled="disabled" value="120"/>
                    </td>
                </tr>

                <tr>
                    <td class="label"><label for="deal_current_qty_ordered"><?php echo $this->__('Ordered Quantity')?></label></td>
                    <td class="value">
                        <input type="text" id="deal_current_qty_ordered" name="deal[current_qty_ordered]" class="input-text" disabled="disabled" value="120"/>
                    </td>
                </tr>
            </tbody>
        </table>
    </fieldset>
</div>